config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/index' => 'static_pages#index'
  get '/posts' => 'posts#index'
  post '/posts/new' => 'posts#create'
  post 'login' => 'users#login'
  post 'clear' => 'static_pages#clear'
  get 'home' => 'static_pages#home'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates_presence_of :content
  validates_length_of :content, maximum: 255, message: "Comment cannot be longer than 255 characters"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    session[:post] = @post
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.content, post %></td>
        <td><%= post.user["username"] %></td>
        <% if !session[:user].nil? %>
          <% if session[:user]["isAdmin"] or session[:user]["id"] == post["user_id"] %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.hidden_field :user_id, :value => session[:user]["id"] %>
	<%= f.submit "Submit" %>
<% end %>
<% if @post.errors %>
	<% @post.errors.each do |e| %>
		<%= "Error: #{e}" %>
	<% end %>
<% end %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <em><%= @post.created_at.strftime("Posted %m/%d/%Y at %I:%M%p") %>:</em> 
  <strong><%= @post.user["username"] %></strong>
  <%= @post.content %>
</p>
<% @post.comments.each do |comment| %>
	<div class="comment">
	<em><%= comment.created_at.strftime("%m/%d/%Y at %I:%M%p") %><%= comment.id %>: </em>
	<strong><%= comment.user.username %></strong>: 
	<%= comment.content %>
	<p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %><p>
	</div>
<% end %>
<%= link_to "New Comment", new_comment_path %>
<% if !session[:user].nil? %>
	<% if session[:user]["isAdmin"] or session[:user]["id"] == @post[:user_id] %>
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
		<%= link_to 'Back', posts_path %>
	<% end %>
<% end %>