config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/index' => 'static_pages#index'
  get '/posts' => 'posts#index'
  post '/posts/new' => 'posts#create'
  post 'login' => 'users#login'
  post 'clear' => 'static_pages#clear'
  get 'home' => 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProjectKyle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  	<% if !flash.empty? %>
	  	<% flash.each do |key, value| %>
	  	<% end %>
	<% end %>
	<% if !session[:user].nil? and !session[:user]["id"].nil?%>
  		<%= link_to session[:user]["username"], user_path(session[:user]["id"]) %>
  		<%= session[:user]["first_name"] %>
  		<%= form_for :user, :url => "/clear" do |f| %>
			<%= f.submit "Logout" %>
		<% end %>
	<% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProjectKyle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<% if session[:user]["isAdmin"] %>
  <body>
  <%= yield %>
<% else %>
	<h1>Access Forbidden</h1>
	<%= link_to "Return to Safety!", posts_path %>
    <% end %>
  </body>
</html>